### PR TITLE
Updated generate_s3_file for actions

### PR DESCRIPTION
**Pull request by thomashale**

### CODE REVIEW

**Comment by thomashale** [comment]
@blakeburch I swear I didn't touch google_auth.py, don't know how that got in there. Will remove it.

>It should allow the options for key_id and SSE
Why? All our S3 buckets are encrypted by default so encrypting the individual files on top of that is unneccessary

**Comment by blakeburch** [comment]
@thomashale 

> Why? All our S3 buckets are encrypted by default so encrypting the individual files on top of that is unneccessary
Try to upload a file and generate the link on `forkliftprod-outputs` without using the kms keyid and SSE. I'm 95% certain when I built out these functions that it wouldn't work without them.

If it does, great! No point in having them defaulted. But these functions should be written to work sustainably for any bucket, not just with our buckets. Reason being is:

- New buckets will come along (like Actions did)
- We want a forklift template that can export to any bucket (client team IT request occasionally) using these functions.

**Comment by thomashale** [comment]
Fixed the KMS keys. They still default to forklift so if you don't have/want them, you've got to explicitly call key_id=None, sse=None

**Comment by thomashale** [comment]
Closing until we have time to work on the "allow any bucket and figure out KMS" enhancement

**Pull request closed without merging**
